# Configuration file for Big Ridge Outdoor Kitchens configurator
---
materialsFile: base-materials.mtl
texturesFolder: textures/
categories:
  - name: '29"'
    modules:

      - name: Double Drawers
        location: modules/29/R29DD
        size:
          width: 29
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2956
        variantId: 2921

      - name: Open
        location: modules/29/R29O
        size:
          width: 29
          depth: 29
        connectableFaces:
          - left
          - right
          - front
          - back
        productId: 2962
        variantId: 2927

      - name: Refridgerator
        location: modules/29/R29R
        size:
          width: 29
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2961
        variantId: 2926

      - name: Single Access Door
        location: modules/29/R29SD
        size:
          width: 29
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2959
        variantId: 2924
        options:
          - required: true
            id: 5555
            name: Hinge Swing Location
            type: radio
            values:
              - label: Left Hinged
                value: 1111
              - label: Right Hinged
                value: 1112

      - name: Single Access Door & Double Burner
        location: modules/29/R29SDB
        size:
          width: 29
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2958
        variantId: 2923

      - name: Single Access Door & Sink
        location: modules/29/R29SDS
        size:
          width: 29
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2957
        variantId: 2922

      - name: Trash Drawer
        location: modules/29/R29T
        size:
          width: 29
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2960
        variantId: 2925

  - name: '48"'
    modules:

      - name: Trash Drawer
        location: modules/48/R48T
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2972
        variantId: 2937

      - name: Trash Drawer & Refrigerator
        location: modules/48/R48TR
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2968
        variantId: 2933

      - name: Trash Drawer, Single Access Door & Double Burner
        location: modules/48/R48TSDB
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2970
        variantId: 2935

      - name: Refrigerator
        location: modules/48/R48R
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2976
        variantId: 2941

      - name: Refrigerator, Single Access Door & Sink
        location: modules/48/R48RSDS_1
        alternatives:
          - location: modules/48/R48RSDS_2
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2973
        variantId: 2938

      - name: Refrigerator & Single Access Door
        location: modules/48/R48RSD
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2975
        variantId: 2940

      - name: Refrigerator, Single Access Door & Double Burner
        location: modules/48/R48RSDB
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2974
        variantId: 2939

      - name: Double Drawers, Single Access Door & Double Burner
        location: modules/48/R48DDSDB
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2966
        variantId: 2931

      - name: Single Door & Sink
        location: modules/48/R48SDS
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2977
        variantId: 2942

      - name: Trash Drawer & Single Access Door
        location: modules/48/R48TSD
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2971
        variantId: 2936

      - name: Single Access Door
        location: modules/48/R48SD
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2979
        variantId: 2944

      - name: Open
        location: modules/48/R48O
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2982
        variantId: 2947

      - name: Double Drawers
        location: modules/48/R48DDO
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2967
        variantId: 2932

      - name: Grill & Double Doors
        location: modules/48/R48GDDO
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2980
        variantId: 2945

      - name: Double Doors
        location: modules/48/R48DD
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2981
        variantId: 2946

      - name: Trash Drawer & Double Drawers
        location: modules/48/R48DDT
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2964
        variantId: 2929

      - name: Refrigerator & Double Drawers
        location: modules/48/R48DDR
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2963
        variantId: 2928

  - name: '71"'
    modules:

      - name: Grill, Double Doors & Double Drawers
        location: modules/71/R71GDDODD
        size:
          width: 71
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2983
        variantId: 2948

      - name: Grill, Double Doors, Double Drawers & Double Side Burner
        location: modules/71/R71GDDODDD
        size:
          width: 71
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2985
        variantId: 2950

      - name: Grill, Double Doors, Single Access Door & Sink
        location: modules/71/R71GDDOSDS
        size:
          width: 71
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2984
        variantId: 2949
