# Configuration file for Big Ridge Outdoor Kitchens configurator
---
materialsFile: base-materials.mtl
texturesFolder: textures/
categories:
  - name: '29"'
    modules:

      - name: Double Drawers
        location: modules/29/R29DD
        size:
          width: 29
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2956

      - name: Open
        location: modules/29/R29O
        size:
          width: 29
          depth: 29
        connectableFaces:
          - left
          - right
          - front
          - back
        productId: 2962

      - name: Refridgerator
        location: modules/29/R29R
        size:
          width: 29
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2961

      - name: Single Access Door
        location: modules/29/R29SD
        size:
          width: 29
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2959

      - name: Single Access Door & Double Burner
        location: modules/29/R29SDB
        size:
          width: 29
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2958

      - name: Single Access Door & Sink
        location: modules/29/R29SDS
        size:
          width: 29
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2957

      - name: Trash Drawer
        location: modules/29/R29T
        size:
          width: 29
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2960

  - name: '48"'
    modules:

      - name: Trash Drawer
        location: modules/48/R48T
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2972

      - name: Trash Drawer & Refrigerator
        location: modules/48/R48TR
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2968


      - name: Trash Drawer, Single Access Door & Double Burner
        location: modules/48/R48TSDB
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2970

      - name: Refrigerator
        location: modules/48/R48R
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2976

      - name: Refrigerator, Single Access Door & Sink
        location: modules/48/R48RSDS_1
        alternatives:
          - location: modules/48/R48RSDS_2
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2973

      - name: Refrigerator & Single Access Door
        location: modules/48/R48RSD
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2975

      - name: Refrigerator, Single Access Door & Double Burner
        location: modules/48/R48RSDB
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2974

      - name: Double Drawers, Single Access Door & Double Burner
        location: modules/48/R48DDSDB
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2966

      - name: Single Door & Sink
        location: modules/48/R48SDS
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2977

      - name: Trash Drawer & Single Access Door
        location: modules/48/R48TSD
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2971

      - name: Single Access Door
        location: modules/48/R48SD
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2979

      - name: Open
        location: modules/48/R48O
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2982

      - name: Double Drawers
        location: modules/48/R48DDO
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2967

      - name: Grill & Double Doors
        location: modules/48/R48GDDO
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2980

      - name: Double Doors
        location: modules/48/R48DD
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2981

      - name: Trash Drawer & Double Drawers
        location: modules/48/R48DDT
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2964

      - name: Refrigerator & Double Drawers
        location: modules/48/R48DDR
        size:
          width: 48
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2963

  - name: '71"'
    modules:

      - name: Grill, Double Doors & Double Drawers
        location: modules/71/R71GDDODD
        size:
          width: 71
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2983

      - name: Grill, Double Doors, Double Drawers & Double Side Burner
        location: modules/71/R71GDDODDD
        size:
          width: 71
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2985

      - name: Grill, Double Doors, Single Access Door & Sink
        location: modules/71/R71GDDOSDS
        size:
          width: 71
          depth: 29
        connectableFaces:
          - left
          - right
        productId: 2984
